stages:
  - docker-build
before_script:
  - aliimage=10.0.0.44:5000/jfq-spider-api:`TZ=CST-8 date '+%Y%m%d-%H%M'`
  - hostname
  - whoami
build_image:
  stage: docker-build

  script:
    - echo $image
    - if [ "`docker images | awk '/^10.0.0.44:5000/ { print $3 }'`" ]; then docker rmi -f $(docker images | awk '/^10.0.0.44:5000/ { print $3 }' ); fi
    - echo "Build Docker Image..."
    - mvn clean install -U  -Dmaven.test.skip=true
    - docker build --no-cache -t $aliimage .
    - echo "Push Image:" $aliimage " to repository..."
    - docker push $aliimage
  only:
    - master